stages:
- test
- docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make deps
  - make test_without_selenium
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - apk add --update make
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - docker build -t registry.gitlab.com/akubicz/se_hello_printer_app .
  - docker push registry.gitlab.com/akubicz/se_hello_printer_app
