stages:
- test
- docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make deps
  - apt-get install -y xvfb
  - apt-get install -y zip
  - apt-get install -y wget
  - apt-get install -y ca-certificates
  - apt-get install -y libnss3-dev libasound2 libxss1 libappindicator3-1 libindicator7 gconf-service libgconf-2-4 libpango1.0-0 xdg-utils fonts-liberation libgbm1
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome*.deb
  - rm google-chrome*.deb
  - wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
  - make test
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - apk add --update make
  - docker login registry.gitlab.com/akubicz/ -u hello-world-deploy -p $${DOCKER_REGISTRY_PASSWORD}
  - docker build -t registry.gitlab.com/akubicz/se_hello_printer_app .
  - docker push registry.gitlab.com/akubicz/se_hello_printer_app
