stages:
- test
- docker_build
test:
  image: "python:3"
  stage: test
  script:
  - make deps
  - apt-get -y install google-chrome-stable
  - wget http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
  - make test
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - apk add --update make
  - docker login registry.gitlab.com/akubicz/ -u hello-world-deploy -p $${DOCKER_REGISTRY_PASSWORD}
  - docker build -t registry.gitlab.com/akubicz/se_hello_printer_app .
  - docker push registry.gitlab.com/akubicz/se_hello_printer_app
