language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
before_script:
  - wget http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
addons:
  apt:
    packages:
      - google-chrome-stable
script:
  - make lint
  - make test
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: sleepy-bastion-27218
  api_key: ${HEROKU_API_KEY}
